#!/usr/bin/env bash
# Installs, configures, and starts the server
apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx start
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
  rewrite ^/redirect_me(.*) http://www.google.com permanent;
		try_files \$uri \$uri/ =404;
	}
}"

echo -e "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default

sudo systemctl reload nginx
sudo systemctl restart nginx
exit