#!/usr/bin/env bash
# Installs, configures, and starts the server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx start
SERVER_CONFIG=\
"server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\troot /var/www/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\tserver_name _;\n\tlocation / {\n    rewrite ^/redirect_me(.*) http://www.google.com permanent;\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}"

echo -e "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default

sudo systemctl reload nginx
sudo systemctl restart nginx
exit