#!/usr/bin/env bash
# Installs, configures, and starts the server
sudo apt-get update
sudo apt-get -y install ufw nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx start
SERVER_CONFIG=\
"server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\troot /var/www/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\tserver_name _;\n\tlocation / {\n    rewrite ^/redirect_me(.*) http://www.google.com permanent;\n\t\ttry_files \$uri \$uri/ =301;\n\t}\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n}"

echo -e "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
service nginx restart