#!/usr/bin/env bash
# configuring a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo service haproxy start

echo 'frontend theproxy
     bind *:80
     default_backend my_backend_servers

backend my_backend_servers
        balance roundrobin
        server web1 54.162.44.53:80
        server web2 100.26.169.91:80' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy reload
