#!/usr/bin/env bash
# This script displays the numbers from 1 to 100 in a list format
# Displays 'FizzBuzz' in multiple of 3 and 5
# Displays 'Fizz' in multiple of 3
# Displays 'Buzz' in multiples of 5

i=1
while [ "$i" -le 100 ];
do
    if [ $((i%3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((i%5)) -eq 0 ]
    then
        echo "Buzz"
    elif [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]
    then
        echo "FizzBuzz"
    else
        echo "$i"
    fi
    ((++i))
done
