#!/usr/bin/env bash
# This script displays "Best School"
#+10 times using the while loop
#+and nested if condition

var=0
while [ "$var" -lt 10 ];
do
    ((++var))
    if [ "$var" -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
done
