#!/usr/bin/env bash
# This script prints 1 to 20
#+using the while loop
#+and nested if condition and case

var=1
while [ "$var" -le 20 ];
do
    case "$var" in
        4) echo "4"
           echo "bad luck from China";;
        9) echo "9"
           echo "bad luck from Japan";;
        17) echo "17"
            echo "bad luck from Italy";;
        *) echo "$var";;
    esac
    ((++var))
done
