#!/usr/bin/env bash
# This bash script gives information about the
#+school file, if it exists or not, if it is
#+empty or not, and if it is a regular file or not

file=school
if [ -e $file ]
then
    echo "school file exists"
    if [ -s $file ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ ! -d $file ]
    then
       echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
